<!--main js-->
<script src="js/jquery-1.12.4.min.js"></script>
<!--bootstrap js-->
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-select.min.js"></script>
<script src="js/slick.min.js"></script>
<script src="js/jquery-ui.js"></script> 
<script src="js/wow.min.js"></script>
<!--custom js-->
<script src="js/custom.js"></script>
